### ISSUE TITLE
http://localhost:8080/ is blank

### ISSUE THREAD

**Issue by ivineel11** [material-motion/direct#21]
http://localhost:8080/ is showing a Blank screen even after installing everything as per the instructions. Any recommended solutions for this, please? @rodydavis 
<img width="1440" alt="Screenshot 2022-02-19 at 1 34 54 PM" src="https://user-images.githubusercontent.com/86518007/154792551-f81c1cd3-7d13-4483-a898-9a3726ae8112.png">

**Comment by rodydavis** [comment]
I added a link on the readme:

https://stackoverflow.com/questions/69465376/app-engine-python-2-7-importerror-cannot-import-name-apiproxy

it will do that if it uses the latest cloud sdk

**Comment by ivineel11** [comment]
Downgraded from google-cloud-sdk-373.0.0 to 359.0.0. But it's still showing a Blank Screen without any contents, only the Favicon is present. Attaching a screenshot of the terminal for your reference @rodydavis
<img width="1440" alt="Screenshot 2022-02-20 at 11 58 03 AM" src="https://user-images.githubusercontent.com/86518007/154831626-68bcdbb4-d90b-4373-b381-c39eea3841da.png">
<img width="1440" alt="Screenshot 2022-02-20 at 12 08 13 PM" src="https://user-images.githubusercontent.com/86518007/154831645-3e9c892f-0eaa-461f-b4be-fba75b342fcd.png">

**Comment by ivineel11** [comment]
Thank you very much @rodydavis
It's working perfectly fine after downgrading the Google Cloud SDK.
